name: Build Docker Container

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string to use"
        type: string
        required: true

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    name: Build Frontend
    with:
      version: ${{ inputs.version }}

  build-backend:
    needs: [build-frontend]
    uses: ./.github/workflows/build-backend.yml
    name: Build Backend
    with:
      version: ${{ inputs.version }}
      frontend-artifact-id: ${{ needs.build-frontend.outputs.artifact-id }}

  build-docker:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu:latest

    steps:
      - name: Checkout repository
        id: checkout-repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          sparse-checkout: |
            docker
            .github
          sparse-checkout-cone-mode: false
          lfs: true

      - name: Download Server
        uses: actions/download-artifact@v5
        with:
          artifact-ids: ${{ needs.build-backend.outputs.artifact-id }}
          path: /docker/app
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: /docker
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/kirvilnet/kirvilnet-mainsite:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
